# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-14 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumeitem',
            name='resume',
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='resumes',
            field=models.ManyToManyField(related_name='items', to='resume.Resume'),
        ),
    ]
